Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -16,7 +16,7 @@ jobs:
     steps:
       - name: "Check dev"
         if: "!contains(fromJson(env.AVAILABLE_DEVS), github.event.inputs.dev)"
-        run: echo "Invalid dev name"
+        run: echo "Invalid dev name" && exit 1
       # Runs a single command using the runners shell
       - name: Run a one-line script
         run: echo Hello, world!
