Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -15,8 +15,10 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: "Check dev"
-        if: ${{ !contains(fromJson(env.AVAILABLE_DEVS), github.event.inputs.dev) }}
-        run: exit 1
+        if: ! contains(fromJson(env.AVAILABLE_DEVS), ${{ github.event.inputs.dev }})
+        run: |
+          echo "Invalid name"
+          exit 1
       # Runs a single command using the runners shell
       - name: Run a one-line script
         run: echo Hello, world!
