v

diff --git a/.github/workflows/multiple-commit.yml b/.github/workflows/multiple-commit.yml
--- a/.github/workflows/multiple-commit.yml
+++ b/.github/workflows/multiple-commit.yml
@@ -18,7 +18,26 @@ jobs:
           token: ${{ secrets.APP_GITHUB_TOKEN }}
           ref: ${{ matrix.branch }}
           fetch-depth: 0
-#      - uses: pr-mpt/actions-merge-branch@v2
+      - name: Set commit author information
+        shell: bash
+        run: |
+            git config user.name "github-actions[bot]"
+            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
+      - name: Cherry pick
+        shell: bash
+        run: |
+          if ! git cherry-pick ${{ github.event.before }}..${{ github.event.after }} --strategy-option theirs
+          then
+              echo "Auto Merge failed. Attempting to use merge tool."
+              yes $conflict_resolution | git mergetool --tool=vimdiff3
+              git clean -f *.orig
+              git commit -m "From Jenkins Job: ${JOB_NAME}  Build: ${BUILD_NUMBER}"
+              echo "Merge successful using merge tool"
+          else
+              echo "Auto Merge successful."
+          fi
+#      - name: Find and replace version branch
+#        uses: mingjun97/file-regex-replace@v1
 #        with:
 #          from: "origin/test3"
 #          push: false
